### ISSUE TITLE
CacheException: net.sf.ehcache.CacheException: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Wizzercn** [Wizzercn/NutzWk#18]
启动报错

javax.servlet.ServletException: Filtered request failed.
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:384)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
root cause

org.apache.shiro.cache.CacheException: net.sf.ehcache.CacheException: java.lang.ClassNotFoundException: cn.wizzer.modules.gm.sys.models.Sys_user

**Comment by Wizzercn** [comment]
清除缓存即可：

ehcahe.xml

    <cache name="shiro-activeSessionCache"
           maxElementsInMemory="1000"
           overflowToDisk="true"
           eternal="true"
           timeToLiveSeconds="0"
           timeToIdleSeconds="0"
           diskPersistent="fale"
           diskExpiryThreadIntervalSeconds="0"/>

diskPersistent改为false
diskExpiryThreadIntervalSeconds改为0

重启即可，可以访问后记得改回去。

**Comment by qyvlik** [comment]
您好，我的项目遇到了如下问题。
```
javax.servlet.ServletException: Filtered request failed. 
    at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:384) 
    at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344) 
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261) 
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:201) 
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178) 
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) 
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:223) 
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:107) 
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) 
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) 
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:75) 
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:934) 
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:90) 
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:494) 
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009) 
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:632) 
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) 
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1592) 
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1550) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
    at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.IllegalArgumentException 
    at org.apache.catalina.webresources.AbstractResourceSet.checkPath(AbstractResourceSet.java:39) 
    at org.apache.catalina.webresources.DirResourceSet.getResource(DirResourceSet.java:91) 
    at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:176) 
    at org.apache.catalina.webresources.CachedResource.validate(CachedResource.java:62) 
    at org.apache.catalina.webresources.Cache.getResource(Cache.java:78) 
    at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:163) 
    at org.apache.catalina.core.StandardContext.getRealPath(StandardContext.java:4528) 
    at org.apache.catalina.core.ApplicationContext.getRealPath(ApplicationContext.java:398) 
    at org.apache.catalina.core.ApplicationContextFacade.getRealPath(ApplicationContextFacade.java:335) 
    at com.opensymphony.module.sitemesh.mapper.FileDecoratorMapper.getNamedDecorator(FileDecoratorMapper.java:48) 
    at com.opensymphony.module.sitemesh.mapper.AbstractDecoratorMapper.getNamedDecorator(AbstractDecoratorMapper.java:50) 
    at com.opensymphony.module.sitemesh.mapper.AbstractDecoratorMapper.getNamedDecorator(AbstractDecoratorMapper.java:50) 
    at com.opensymphony.module.sitemesh.mapper.AbstractDecoratorMapper.getNamedDecorator(AbstractDecoratorMapper.java:50) 
    at com.opensymphony.module.sitemesh.mapper.PageDecoratorMapper.getByProperty(PageDecoratorMapper.java:70) 
    at com.opensymphony.module.sitemesh.mapper.PageDecoratorMapper.getDecorator(PageDecoratorMapper.java:62) 
    at com.opensymphony.module.sitemesh.mapper.AbstractDecoratorMapper.getDecorator(AbstractDecoratorMapper.java:45) 
    at com.opensymphony.module.sitemesh.mapper.InlineDecoratorMapper.getDecorator(InlineDecoratorMapper.java:41) 
    at com.opensymphony.sitemesh.compatability.DecoratorMapper2DecoratorSelector.selectDecorator(DecoratorMapper2DecoratorSelector.java:30) 
    at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:83) 
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
    at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) 
    at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) 
    at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) 
    at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) 
    at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) 
    at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) 
    ... 29 more 
```

通过清理缓存不起作用。

**Comment by Wizzercn** [comment]
@qyvlik jdk8  tomcat8/9

**Comment by qyvlik** [comment]
@Wizzercn 谢谢您的解答，由于是项目中设置了多个过滤器，在进行链式调用的时候，某个过滤器丢异常了，所以让我怀疑是 shiro 的问题。现在好像是 SiteMeshFilter 的问题。

**Comment by Wizzercn** [comment]
@qyvlik ....好多问题都是如此，喝杯茶回来看看就知道问题出在哪了.

**Comment by qyvlik** [comment]
@Wizzercn 

```
Caused by: java.lang.IllegalArgumentException: null
	at org.apache.catalina.webresources.AbstractResourceSet.checkPath(AbstractResourceSet.java:39) ~[catalina.jar:8.0.0-RC1]
	at org.apache.catalina.webresources.DirResourceSet.getResource(DirResourceSet.java:91) ~[catalina.jar:8.0.0-RC1]
	at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:176) ~[catalina.jar:8.0.0-RC1]
	at org.apache.catalina.webresources.CachedResource.validate(CachedResource.java:62) ~[catalina.jar:8.0.0-RC1]
	at org.apache.catalina.webresources.Cache.getResource(Cache.java:78) ~[catalina.jar:8.0.0-RC1]
	at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:163) ~[catalina.jar:8.0.0-RC1]
	at org.apache.catalina.core.StandardContext.getRealPath(StandardContext.java:4528) ~[catalina.jar:8.0.0-RC1]
	at org.apache.catalina.core.ApplicationContext.getRealPath(ApplicationContext.java:398) ~[catalina.jar:8.0.0-RC1]
	at org.apache.catalina.core.ApplicationContextFacade.getRealPath(ApplicationContextFacade.java:335) ~[catalina.jar:8.0.0-RC1]
```

具体问题就是这个 `org.apache.catalina.webresources.AbstractResourceSet.checkPath`。是 tomcat 的问题吗？

**Comment by qyvlik** [comment]
项目算是跑起来了，之前用的 `apache-tomcat-8.0.0-RC1` 是没问题的，然后跑了另外一个项目，然后切回来时，就不行了，现在换成 `apache-tomcat-7.0.67` 就可以了。应该还是 tomcat 获取 webresources 的问题。
