### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by mamacmm** [Wizzercn/NutzWk#24]
七月 13, 2016 10:56:34 上午 org.apache.tomcat.util.digester.SetPropertiesRule begin
警告: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.j2ee.server:nutzwk' did not find a matching property.
七月 13, 2016 10:56:34 上午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["http-nio-8080"]
七月 13, 2016 10:56:34 上午 org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
信息: Using a shared selector for servlet write/read
七月 13, 2016 10:56:34 上午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["ajp-nio-8009"]
七月 13, 2016 10:56:34 上午 org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
信息: Using a shared selector for servlet write/read
七月 13, 2016 10:56:34 上午 org.apache.catalina.startup.Catalina load
信息: Initialization processed in 1398 ms
七月 13, 2016 10:56:34 上午 org.apache.catalina.core.StandardService startInternal
信息: Starting service Catalina
七月 13, 2016 10:56:34 上午 org.apache.catalina.core.StandardEngine startInternal
信息: Starting Servlet Engine: Apache Tomcat/8.0.5
七月 13, 2016 10:56:35 上午 org.apache.catalina.util.SessionIdGenerator createSecureRandom
信息: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [153] milliseconds.
七月 13, 2016 10:56:39 上午 org.apache.catalina.core.StandardContext filterStart
严重: Exception starting filter ShiroFilter
java.lang.ClassCastException: org.apache.shiro.web.servlet.ShiroFilter cannot be cast to javax.servlet.Filter
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:258)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4575)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5185)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1388)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

七月 13, 2016 10:56:39 上午 org.apache.catalina.core.StandardContext filterStart
严重: Exception starting filter nutz
java.lang.ClassCastException: org.nutz.mvc.NutFilter cannot be cast to javax.servlet.Filter
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:258)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4575)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5185)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1388)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

七月 13, 2016 10:56:39 上午 org.apache.catalina.core.StandardContext startInternal
严重: Error filterStart
七月 13, 2016 10:56:39 上午 org.apache.catalina.core.StandardContext startInternal
严重: Context [/nutzwk] startup failed due to previous errors
七月 13, 2016 10:56:39 上午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-nio-8080"]
七月 13, 2016 10:56:39 上午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["ajp-nio-8009"]
七月 13, 2016 10:56:39 上午 org.apache.catalina.startup.Catalina start
信息: Server startup in 4780 ms

**Comment by mamacmm** [comment]
可能是tomcat的问题，使用的tomcat8.0.5报错，换成8.0.36就没问题了

**Comment by Wizzercn** [comment]
一般是配置问题
